[package]
name = "minimap2"
version = "0.1.6"
edition = "2021"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Bindings to libminimap2"
repository = "https://github.com/jguhlin/minimap2-rs"
categories = ["science"]
keywords = ["bioinformatics", "fasta", "alignment", "fastq"]
exclude = [
	"**/*.fasta",
	"libsfasta/test_data/",
	"*.profdata",
]

[dependencies]
libc = "0.2.134"
bytelines = "2.4.0"
simdutf8 = "0.1.4"
flate2 = { version = "1.0.17", features = ["zlib-ng"], default-features = false }

# Dep for development
# minimap2-sys = { path = "./minimap2-sys" }
minimap2-sys = "0.1.5"
fffx = "0.1.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units  = 1

[profile.dev]
debug = true

[profile.dev.package."*"]
opt-level = 3
