[package]
name = "minimap2"
version = "0.1.0"
edition = "2021"
authors = ["Joseph Guhlin <joseph.guhlin@gmail.com>"]
links = "libminimap"

[dependencies]
libc = "0.2.134"
libz-sys = { version = "1.1.0", default-features = false, features = ["libc"] }

[build-dependencies.bindgen]
optional = true
version = "0.60"
default-features = false
features = ["runtime", "which-rustfmt"]

[build-dependencies.cc]
version = "1.0.45"
features = ["parallel"]

[features]
default = ["bindgen"]
