[package]
name = "minimap2-sys"
version = "0.1.0"
edition = "2021"
links = "libminimap2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.134"
# libz-sys = { version = "1.1.0", default-features = false, features = ["libc"] }

[build-dependencies]
pkg-config = "0.3.25"
# libz-sys = { version = "1.1.0", default-features = false, features = ["libc"] }

[build-dependencies.bindgen]
optional = true
version = "0.60"
default-features = false
features = ["runtime", "which-rustfmt"]

[build-dependencies.cc]
version = "1.0.45"
features = ["parallel"]

[features]
default = ["bindgen"]
