[package]
name = "minimappers2"
version = "0.1.3"
edition = "2021"

[lib]
name = "minimappers2"
crate-type = ["cdylib"]

[dependencies]
# fffx = "0.1.2"

minimap2 = { version = "0.1.11", features = ["simde"] }
minimap2-sys = { version = "0.1.10", features = ["simde"] }
#minimap2 = { path = "../", features = ["simde"] }
#minimap2-sys = { path = "../minimap2-sys", features = ["simde"] }
crossbeam = "0.8.2"
mimalloc = {version = "0.1.34", default-features = false }

pyo3 = { version = "0.18.1" }
polars = "0.27.2"
pyo3-polars = "0.2.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units  = 1

[profile.dev]
debug = true

[profile.dev.package."*"]
opt-level = 3

[features]
default = ["pyo3/extension-module", "pyo3/abi3-py37"]