name: Rust

on:
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'src/'
      - 'Cargo.toml'
      - 'test_data/'   
env:
  CARGO_TERM_COLOR: always

jobs:
  test-musl:
    runs-on: ubuntu-latest
    container: messense/rust-musl-cross:x86_64-musl
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test
    - name: Run tests htslib
      run: cargo test --features htslib

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests htslib
      run: cargo test --features htslib
    - name: Run tests mm2-fast
      run: cargo test --features mm2-fast
    - name: Run tests simde
      run: cargo test --features simde

  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests htslib
      run: cargo test --features htslib
    - name: Run tests simde
      run: cargo test --features simde
