name: Rust

on:
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'minimap2-sys/'

env:
  CARGO_TERM_COLOR: always

jobs:
  test-musl:
    runs-on: ubuntu-latest
    container: messense/rust-musl-cross:x86_64-musl
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test
    - name: Run tests htslib
      run: cargo test --features htslib
    - run: cd minimap2-sys
    - name: Run minimap2-sys tests
      run: cargo test
    - name: Run minimap2-sys simde tests
      run: cargo test --features simde
    - run: cd ..
    - run: cd minimappers2
    - name: Run minimappers2 Rust testss
      run: cargo test

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests htslib
      run: cargo test --features htslib
    - name: Run tests mm2-fast
      run: cargo test --features mm2-fast
    - name: Run tests simde
      run: cargo test --features simde
    - run: cd minimap2-sys
    - name: Run minimap2-sys tests
      run: cargo test
    - name: Run minimap2-sys mm2-fast tests
      run: cargo test --features mm2-fast
    - name: Run minimap2-sys simde tests
      run: cargo test --features simde
    - run: cd ..
    - run: cd minimappers2
    - name: Run minimappers2 Rust testss
      run: cargo test
      
  build-manylinux-x64_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Publish wheel
        uses: messense/maturin-action@v1
        env:
          RUSTFLAGS: -C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma
        with:
          rust-toolchain: nightly-2023-01-19
          maturin-version: '0.14.10'
          command: build
          args: -m minimappers2/Cargo.toml
